config/routes.rb
Rails.application.routes.draw do
  resources :alumnis
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'students#index', as: :root
end

app/models/alumni.rb
class Alumni < ApplicationRecord

    has_many :students, through: :connections

    def proper_name
      "#{first_name} #{last_name}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord

    belongs_to :alumni
    belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    mount_uploader :photo, PhotoUploader

    has_many :alumni, through: :connections

    def proper_name
        "#{first_name} #{last_name}"
      end
end

app/controllers/alumnis_controller.rb
class AlumnisController < ApplicationController
  before_action :set_alumni, only: [:show, :edit, :update, :destroy]

  # GET /alumnis
  # GET /alumnis.json
  def index
    @alumnis = Alumni.all
  end

  # GET /alumnis/1
  # GET /alumnis/1.json
  def show
  end

  # GET /alumnis/new
  def new
    @alumni = Alumni.new
  end

  # GET /alumnis/1/edit
  def edit
  end

  # POST /alumnis
  # POST /alumnis.json
  def create
    @alumni = Alumni.new(alumni_params)

    respond_to do |format|
      if @alumni.save
        format.html { redirect_to alumnis_path, notice: 'Alumni was successfully created.' }
        format.json { render :show, status: :created, location: @alumni }
      else
        format.html { render :new }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnis/1
  # PATCH/PUT /alumnis/1.json
  def update
    respond_to do |format|
      if @alumni.update(alumni_params)
        format.html { redirect_to @alumni, notice: 'Alumni was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumni }
      else
        format.html { render :edit }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnis/1
  # DELETE /alumnis/1.json
  def destroy
    @alumni.destroy
    respond_to do |format|
      format.html { redirect_to alumnis_url, notice: 'Alumni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumni
      @alumni = Alumni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumni_params
      params.require(:alumni).permit(:first_name, :last_name, :email, :grad_year, :phone, :degree)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :year, :phone, :photo)  
    end
end

app/helpers/alumnis_helper.rb
module AlumnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/alumnis/_form.html.erb
<div id="form">
<%= form_for @alumni do |f| %>
    <% if @alumni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumni.errors.count, "error") %> prohibited this alumni from being saved:</h2>

      <ul>
      <% @alumni.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field juxtapose_l">
      <p>
        <%#= f.label :first_name %> <br />
        <%= f.text_field :first_name, size: 10, placeholder: 'First Name' %>
      </p>
    </div>
    <div class="field juxtapose_r">
      <p>
        <%#= f.label :last_name %> <br />
        <%= f.text_field :last_name, placeholder: 'Last Name' %>
      </p>
    </div>

    <div >
      <p >
        <%#= f.label :email, "* Email Address" %> <br />
        <%= f.text_field :email, placeholder: 'Email' %>
      </p>
    </div>

    <div class="field juxtapose_l">
      <p>
        <%#= f.label :email, "* Email Address" %> 
        <%= f.text_field :phone, placeholder: 'Phone' %>
      </p>
    </div>

    <div class="field juxtapose_r">
      <p>
        <%#= f.label :email, "* Email Address" %> 
        
        <%= f.text_field :grad_year, placeholder: 'Graduation Year' %>
      </p>
    </div>

    <p>
        <%= f.text_field :degree, placeholder: 'Degree' %>
  </p>
  <br />
  <p><%= f.submit (@alumni.new_record? ? "Sign up" : "Update"), class: "button" %></p>
<% end %>
</div>

app/views/alumnis/edit.html.erb
<h1>Editing Alumni</h1>

<%= render 'form', alumni: @alumni %>

<%= link_to 'Show', @alumni %> |
<%= link_to 'Back', alumnis_path %>

app/views/alumnis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumni</h1>

<table>
  <thead>
    <tr>
      <th colspan="1" >Name</th>
    </tr>
  </thead>

  <tbody>
    <% @alumnis.each do |alumni| %>
      <tr>
        <td> <%= link_to alumni.proper_name, alumni_path(alumni), {:style=>'color: #cc002b;'} %> </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumni', new_alumni_path, class: 'button' %>

app/views/alumnis/new.html.erb
<%= link_to 'Back', alumnis_path %>
<h1>New Alumni</h1>

<%= render 'form', alumni: @alumni %>

app/views/alumnis/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <b>Name</b>: <%= @alumni.proper_name %>
</h3><br>

<p>
  <b>Email</b>: <%= mail_to @alumni.email, @alumni.email, encode: "javascript" %>
</p>

<p>
  <b>Phone</b>: <%= @alumni.phone %>
</p>

<%= link_to 'Edit', edit_alumni_path(@alumni) %> |
<%= link_to 'Back', alumnis_path %> |
<td><%= link_to 'Destroy', @alumni, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avenue</title>
    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    "general" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => "partials/nav" %>

    <div class="row" id="main_div">
      <div class="small-12 columns" id="main_content">
        <%= yield %>
        <div class="push"></div>
      </div>
    </div>

    <footer>
      <div class="small-12 columns" id="footer">
        <%= render partial: 'partials/footer' %>
      </div>
    </footer> 

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
<div id="footer-links">
    
</div>
    <br/>
    
    <div id="signature">
        Webmaster: <%= mail_to("sallyz@andrew.cmu.edu", "Sally Zhao", encode: "javascript") %> 
        &nbsp;&nbsp;&copy 2017
    </div>
    
    <br/>

</footer>

app/views/partials/_nav.html.erb
<div class="contain-to-grid" >
  <nav class="top-bar" data-topbar role="navigation"> 
    <section class="top-bar-section" id="navbar">
      <ul >
        <!-- link to home -->
        <li><%= link_to image_tag("logo.png"), root_path, id: "logo" %></li>

        <!-- options for items -->
        <span id="links">
            <li class="has-dropdown">
              <%= link_to "STUDENTS", students_path %>
            </li>

            <li class="has-dropdown">
              <%= link_to "ALUMNI", alumnis_path %>
            </li>

          <li class="has-dropdown right">
            <%#= link_to current_user.first_name.upcase, user_path(current_user) %>
            <%= link_to "MY ACCOUNT", students_path %>
            <ul class="dropdown">
              <li><%#= link_to "Settings", students_path %></li>
              <li><%#= link_to 'Logout', students_path %></li>
            </ul>
          </li>

      </span><!-- links -->
      </ul>
    </section>
  </nav>
</div>

app/views/students/_form.html.erb
<div id="form">
<%= simple_form_for @student, :html => { :multipart => true } do |f| %>
    <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field juxtapose_l">
      <p>
        <%#= f.label :first_name %> <br />
        <%= f.text_field :first_name, size: 10, placeholder: 'First Name' %>
      </p>
    </div>
    <div class="field juxtapose_r">
      <p>
        <%#= f.label :last_name %> <br />
        <%= f.text_field :last_name, placeholder: 'Last Name' %>
      </p>
    </div>

    <div >
      <p >
        <%#= f.label :email, "* Email Address" %> <br />
        <%= f.text_field :email, placeholder: 'Email' %>
      </p>

      <p>
        <%#= f.label :email, "* Email Address" %> 
        <%= f.text_field :phone, placeholder: 'Phone' %>
      </p>
    </div>

    <p>
        <%= f.select :year, [['Freshman', 'freshman'],['Sophomore', 'sophomore'],['Junior', 'junior'], ['Senior', 'senior']], :prompt => "Select year..." %>
  </p>
  
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <br />
  <p><%= f.submit (@student.new_record? ? "Sign up" : "Update"), class: "button" %></p>
<% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h3 >Students</h3>

<table>
  <thead>
    <tr>
      <th colspan="4"> Name </th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td> <%= link_to student.proper_name, student_path(student), {:style=>'color: #cc002b;'} %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: 'button' %>

app/views/students/new.html.erb
<%= link_to 'Back', students_path, {:style=>'color: #cc002b;'} %>
<h3>New Student</h3>

<%= render 'form', student: @student %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @student.photo_url.nil? %>
    <p><%= image_tag @student.photo_url %></p>
  <% end %>

<h3>
  <b>Name</b>: <%= @student.proper_name %>
</h3><br>

<p>
  <b>Email</b>: <%= mail_to @student.email, @student.email, encode: "javascript" %>
</p>

<p>
  <b>Phone</b>: <%= @student.phone %>
</p>

<p>
  <b>Year</b>: <%= @student.year.capitalize %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %> |
 <td><%= link_to 'Destroy', @student, method: :delete, data: { confirm: 'Are you sure?' } %></td>